CREATE TABLE IF NOT EXISTS `characters` (
  `License` varchar(255) DEFAULT NULL,
  `User` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `SID` int(11) NOT NULL AUTO_INCREMENT,
  `First` varchar(255) DEFAULT NULL,
  `Last` varchar(255) DEFAULT NULL,
  `Gender` int(11) NOT NULL DEFAULT 0,
  `New` tinyint(1) NOT NULL DEFAULT 1,
  `Jailed` tinyint(1) NOT NULL DEFAULT 0,
  `Origin` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Apps` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Wardrobe` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `DOB` longtext DEFAULT NULL,
  `Cash` bigint(20) DEFAULT NULL,
  `LastPlayed` longtext DEFAULT NULL,
  `Jobs` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Apartment` int(11) DEFAULT NULL,
  `PhoneSettings` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Phone` varchar(255) DEFAULT NULL,
  `Crypto` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Licenses` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Alias` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `PhonePermissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `PhonePosition` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Addiction` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Animations` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Armor` int(11) NOT NULL DEFAULT 0,
  `BankAccount` int(11) DEFAULT NULL,
  `CryptoWallet` varchar(255) DEFAULT NULL,
  `HP` int(11) DEFAULT 200,
  `HPReductions` int(11) DEFAULT 0,
  `States` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Callsign` varchar(255) DEFAULT NULL,
  `MDTHistory` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Flags` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Qualifications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `LastClockOn` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Salary` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `TimeClockedOn` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Reputations` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `GangChain` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Bio` varchar(255) DEFAULT NULL,
  `JailedData` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `ICU` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Deleted` tinyint(1) DEFAULT 0,
  `Status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `Parole` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `MDTSystemAdmin` tinyint(1) NOT NULL DEFAULT 0,
  `LaptopSettings` longtext DEFAULT NULL,
  `LaptopPermissions` longtext DEFAULT NULL,
  `LaptopApps` longtext DEFAULT NULL,
  `HUDConfig` longtext DEFAULT NULL,
  `Mugshot` varchar(255) DEFAULT NULL,
  `Attorney` tinyint(1) DEFAULT 0,
  `MDTSuspension` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
  `DrugStates` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `CasinoChips` LONGTEXT DEFAULT NULL,
  `LSUNDGInviter` JSON DEFAULT NULL,
  `LSUNDGBan` JSON DEFAULT NULL,
  PRIMARY KEY (`SID`) USING BTREE,
  CONSTRAINT `Origin` CHECK (json_valid(`Origin`)),
  CONSTRAINT `Apps` CHECK (json_valid(`Apps`)),
  CONSTRAINT `Wardrobe` CHECK (json_valid(`Wardrobe`)),
  CONSTRAINT `Jobs` CHECK (json_valid(`Jobs`)),
  CONSTRAINT `PhoneSettings` CHECK (json_valid(`PhoneSettings`)),
  CONSTRAINT `Crypto` CHECK (json_valid(`Crypto`)),
  CONSTRAINT `Licenses` CHECK (json_valid(`Licenses`)),
  CONSTRAINT `Alias` CHECK (json_valid(`Alias`)),
  CONSTRAINT `PhonePermissions` CHECK (json_valid(`PhonePermissions`)),
  CONSTRAINT `Addiction` CHECK (json_valid(`Addiction`)),
  CONSTRAINT `Animations` CHECK (json_valid(`Animations`)),
  CONSTRAINT `States` CHECK (json_valid(`States`)),
  CONSTRAINT `MDTHistory` CHECK (json_valid(`MDTHistory`)),
  CONSTRAINT `Flags` CHECK (json_valid(`Flags`)),
  CONSTRAINT `Qualifications` CHECK (json_valid(`Qualifications`)),
  CONSTRAINT `LastClockOn` CHECK (json_valid(`LastClockOn`)),
  CONSTRAINT `Salary` CHECK (json_valid(`Salary`)),
  CONSTRAINT `TimeClockedOn` CHECK (json_valid(`TimeClockedOn`)),
  CONSTRAINT `Reputations` CHECK (json_valid(`Reputations`)),
  CONSTRAINT `GangChain` CHECK (json_valid(`GangChain`)),
  CONSTRAINT `JailedData` CHECK (json_valid(`JailedData`)),
  CONSTRAINT `ICU` CHECK (json_valid(`ICU`)),
  CONSTRAINT `Status` CHECK (json_valid(`Status`)),
  CONSTRAINT `Parole` CHECK (json_valid(`Parole`)),
  CONSTRAINT `DrugStates` CHECK (json_valid(`DrugStates`)),
  CONSTRAINT `CasinoChips` CHECK (json_valid(`CasinoChips`)),
  CONSTRAINT `LSUNDGInviter` CHECK (json_valid(`LSUNDGInviter`)),
  CONSTRAINT `MDTSuspension` CHECK (json_valid(`MDTSuspension`))
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;